### ISSUE TITLE
Using pub key for encryption

### ISSUE THREAD

**Issue by vaporup** [sfstpala/zpy#3]
Hi,

I like your tool.
Wouldn't it be better to encrypt the file using the public key and decrypt with the private key?
So you could encrypt files with the public key of someone and share it over the internet.
Like GPG

**Comment by sfstpala** [comment]
Hi,

that is definitely possible, but I don't really want to attempt to rebuild GPG. :)

By the way: you may also like [SSH Vault](https://ssh-vault.com/).

**Comment by sfstpala** [comment]
Hi Sven,

I misread your comment at first. Zpy uses the public key to encrypt files and the private key to decrypt them. You can totally use it to send stuff to people whose RSA public key you have.

Just type:

    ~ $ echo "hello :)" | zpy encrypt -i someone-else.pub > message-from-sven.zpy

And then the other person, presuming that you have their primary default public key, just goes:

    ~ $ zpy decrypt message-from-sven.zpy 
    hello :)

**Comment by vaporup** [comment]
Ah ok. Thank you for clarification. I agree it should not replace GPG but often the other person doesn't have GPG yet but you have their SSH public Key and can quickly send something without setting up GPG first...

**Comment by sfstpala** [comment]
Just to elaborate on this: the missing component is trust. I.e. how do you know that you're sending it to the person and not to a man in the middle or an imposter.

In theory (and in practice, actually), that renders the system unsuitable for communication. However you can of course decide on a case-by-case basis how confident you are that you actually have the correct public key. And there are lots of situations where it would be totally okay, just as you say.

SSH Vault goes a step further in that it offers you to get the public key from GitHub. That makes it easy to send a message to someone, but it assumes you trust GitHub. GPG, in contrast to that, lets other people sign keys and thereby increase the level of trust you can have in them, and it also stores that information on a decentralised network of key servers.

If I added all of the stuff you need (identity, key servers, signing public keys,  revocation, expiration) to Zpy, I would just end with a toy clone of GPG.

You probably know all of this, I just wanted to explain why I think Zpy or any of those "GPG made easy" solutions, in my opinion, are no good for talking to people. Why GPG is the gold standard.
